version: '3.0'

expectations:
  population_size: 10000

actions:

  generate_study_population:
    run: cohortextractor:latest generate_cohort --study-definition study_definition
      --output-format feather
    outputs:
      highly_sensitive:
        cohort: output/input.feather
  stage0_data_cleaning:
    run: r:latest analysis/stage0_data_cleaning.R
    needs:
    - generate_study_population
    outputs:
      highly_sensitive:
        cohort: output/input_stage0.rds
  stage1_define_eligible_population:
    run: r:latest analysis/stage1_define_eligible_population.R
    needs:
    - stage0_data_cleaning
    outputs:
      highly_sensitive:
        cohort: output/input_stage1.rds
      moderately_sensitive:
        flow_chart_csv: output/flow_chart.csv
        flow_chart_html: output/flow_chart.html
  table_1:
    run: r:latest analysis/table_1.R
    needs:
    - stage1_define_eligible_population
    outputs:
      moderately_sensitive:
        descriptive_table_CSV: output/table_1.csv
        descriptive_table_HTML: output/table_1.html
  figure_1:
    run: r:latest analysis/figure_1.R
    needs:
    - stage1_define_eligible_population
    outputs:
      moderately_sensitive:
        Figure_long_covid_cases: output/figure_1.svg
  table_2:
    run: r:latest analysis/table_2.R
    needs:
    - stage1_define_eligible_population
    outputs:
      moderately_sensitive:
        incidence_rate_table_CSV: output/table_2.csv
        incidence_rate_talbe_HTML: output/table_2.html
  table_3:
    run: r:latest analysis/table_3.R
    needs:
    - stage1_define_eligible_population
    outputs:
      moderately_sensitive:
        incidence_rate_table_CSV: output/table_3.csv
        incidence_rate_talbe_HTML: output/table_3.html
  suppl_figure_1:
    run: r:latest analysis/suppl_figure_1.R
    needs:
    - stage1_define_eligible_population
    outputs:
      moderately_sensitive:
        pie_chart_long_covid_code: output/suppl_figure_1.svg 
        table_csv_long_covid_code: output/suppl_figure_1_data.csv
        table_html_long_covid_code: output/suppl_figure_1_data.html
  suppl_figure_2:
    run: r:latest analysis/suppl_figure_2.R
    needs:
    - stage1_define_eligible_population
    outputs:
      moderately_sensitive:
        figure_monthly_long_covid: output/suppl_figure_2.svg     
        table_csv_monthly_long_covid: output/suppl_figure_2_data.csv  
        table_html_monthly_long_covid: output/suppl_figure_2_data.html    
        